# Generated by Django 3.0.5 on 2020-12-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='street_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='street_address_num',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
