# Generated by Django 3.0.5 on 2020-12-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201221_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='street_address_zipcode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
