# Generated by Django 3.0.5 on 2020-12-22 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201221_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='street_address_zipcode',
            new_name='zipcode',
        ),
        migrations.RemoveField(
            model_name='member',
            name='street_address_num',
        ),
    ]
