# Generated by Django 3.0.5 on 2020-12-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201221_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(null=True)),
                ('members', models.ManyToManyField(to='accounts.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('attendees', models.ManyToManyField(to='accounts.Member')),
            ],
        ),
    ]
